<?php
include_once('fgcf.php');
add_action('admin_menu', 'fgcf_menu_page');
function fgcf_menu_page() {
    add_menu_page('Fgcf', 'Contact Popup', 'manage_options', 'Fgcf_page', 'Fgcf_setting_page', '', 200);
}
function fgcf_add_style() {
    wp_enqueue_style('form_style', plugins_url('css/form_style.css', __FILE__));
    wp_enqueue_style('form_style_sheet', plugins_url('css/style.css', __FILE__));
	wp_enqueue_style('form1_style1_sheet1', plugins_url('css/style1.css', __FILE__));
}
add_action("init", "fgcf_add_style");
function fgcf_popup_script() {
    wp_enqueue_script('script_popup', plugins_url('js/popup.js', __FILE__), array('jquery-ui-dialog'));
}
add_action('init', 'fgcf_popup_script');

function Fgcf_setting_page() {
    $url = plugins_url();
    ?><div id="con_of_container" class="wrap">
	<form id="con_ofform" action="" method="POST">
<div id="con_header">
<div class="con_logo">
<h2> Contact Popup</h2>
</div>
<a target="#">
<div class="con_icon-option"><h3><a style="text-decoration:none;" href="http://www.formget.com/app/" target="blank">Try FormGet now</a></h3></div>
</a>
<div class="clear"></div>
</div>
	<div id="con_main">
	<div id="con_of-nav">
		<ul>
			<li> <a  class="pn-view-a" href="#pn_generalsettings" title="Contact Form">Entries</a></li>
			<li> <a class="pn-view-a" href="#pn_content" title="Form Builder">Form Builder</a></li>
			<li> <a class="pn-view-a" href="#pn_displaysetting" title="Embed Code">Embed Code</a></li>
			<li> <a class="pn-view-a" href="#pn_template" title="Help">Help</a></li>		
		</ul>
		</div>
		<div id="con_content">
		<div class="con_group" id="pn_generalsettings">
			<h2>Entries</h2>
			<div class="con_section section-text ">
				<?php
				 Fgcf::fgcf_show_data();
                ?>
			</div>
		</div>
		<div class="con_group" id="pn_content">
		<h2>Form Builder</h2>
			<div class="con_section section-text">
<h3 class="con_heading"> Create your form using FormGet Form Builder</h3>
			<iframe src="http://www.formget.com/app" name="iframe" id="iframebox" style="width:1000px; height:950px; border:1px solid #dfdfdf;">
		</iframe>
			</div>
		</div>	
		<div class="con_group" id="pn_displaysetting">
		<h2>Embed Code</h2>
			<div class="con_section section-text">
			<h3 class="con_heading">Paste here Sliding Form code or Embed Full Form(plain form) code generated by FormGet Form Builder</h3>
		<div class="option">
			<div class="con_controls">
			<textarea name="content[html]" cols="60" rows="10"   class="regular-text"  id="con_content_html" style="width:900px"><?php echo Fgcf::embeded_code() ?></textarea>
			<div id="embed_code_err" style="color:red; display:none;"></div>
			<div id="loader_img" align="center" style="margin-left:460px; display:none;">
    <img src="<?php echo plugins_url('image/ajax-loader.gif', __FILE__);?>">
</div>
			</div>
		</div>
		</div>
		</div>
	<div class="con_group" id="pn_template">
		<h2>Steps to use Popup Contact Plugin</h2>
		
			<div class="con_section section-text">
			<h3></h3>
             <div id="help_txt" style="width:900px;">
              <ol class="step_ol">
             <li class="step_li">We have provided the dummy contact form. Now you can build your form acording to your requirement by using "Form Builder" menu.</br></br></li></br>
			 <li class="step_li">First go to "Form Builder" and then create your form.</br></br></li></br>
			 <li class="step_li">Your form is created now. In order to include it on your website, go to "Embed Form" link.</br></br>
			</li></br>
			 <li class="step_li">You can use "Embed Sliding Form" and "Embed Full Form" tab to get code. Now copy the code by just a single click on "Copy Code" button.</br></br>
			 </li></br>
		 	 <li class="step_li">Paste the above code on "Embed Code" section which appear on left sidebar menu of "Contact Popup" plugin dashboard.</br></br>
			 </li></br>
			 <li class="step_li">Now your contact form appear on your Website which automatically overrite the dummy contact form.</li>
			</ol>
			</div>
			</div>
			
		</div>
		</div>
		<div class="clear"></div>
		</div>
		
		<div class="con_save_bar_top">
		
		<input id="submit-form" class="con_embed_code_save button-primary" type="button" value="Save Changes" name="submit_form" style="display:none;">
		
		</div>
		
		</form>
</div>
		
		   <div id="update_div" style="display:none;"><img id="close_popup_img" src="<?php echo plugins_url("image/close_popup.png", __FILE__); ?>" /><?php Fgcf::fgcf_update_form_entry(); ?></div>
			<div id="delete_div" style="display:none;"><img id="close_popup_img" src="<?php echo plugins_url("image/close_popup.png", __FILE__); ?>" /><div id="delete_head">Do you want to delete?</div>
			</br>
			<input type="button" id="yes_del" name="yes_del" value="Yes">
			<input type="button" id="no_del" name="no_del" value="No"></div>
			<?php
            }
// Delete record from the Database
           /* if (isset($_GET['fgcf_del'])) {
                $id = $_GET['fgcf_del'];
				$result = Fgcf::fgcf_delete_data($id);
                if ($result == true) {
                    $site_url = site_url() . '/wp-admin/admin.php?page=Fgcf_page';
                    header('Location:' . $site_url);
                    exist();
                }
            }*/
            if (isset($_POST['fgcf_form_id'])) {
                $id = $_POST['fgcf_form_id'];
                $result = Fgcf::fgcf_update_data($id);
                if ($result == true) {
					$site_url = site_url() . '/wp-admin/admin.php?page=Fgcf_page';
                    header('Location:' . $site_url);
                    exist();
                }
            }
         function embeded_script() {
			wp_enqueue_script('embeded_script', plugins_url('js/ajax.js', __FILE__), array('jquery'));
            wp_localize_script('embeded_script', 'script_call', array('ajaxurl' => admin_url('admin-ajax.php')));
        }
        add_action('init', 'embeded_script');
        function fgcf_text_ajax_process_request() {
			$text_value = $_POST['value'];
			$text_value = trim($text_value);
			if($text_value == '' || $text_value == null)
			{
			update_option('fg_embed_code', $text_value);
			echo "Please enter valid embed code.";
			}
			elseif ((strpos($text_value, 'iframe') == false) && (strpos($text_value, 'sideBar') == false)){
				echo "Please enter valid embed code.";
			} else{
				update_option('fg_embed_code', $text_value);
				echo "updated";
			}
			die(0);
		  }
        add_action('wp_ajax_master_response', 'fgcf_text_ajax_process_request');
        //add_action('wp_ajax_nopriv_master_response', 'fgcf_text_ajax_process_request');
        ?>